FN_TARGET_FEATURE = ["VULNERABLE"]
FN_UNIMPORTANT_FEATURES = ["Function ID", "Function Name"]
FN_CPP_MEMORY_FEATURES = ["MemOps"]
FN_EXPLICIT_EXCLUDE_FEATURES = ["InDirectCalls"]
####
BB_TARGET_FEATURE = ["VULNERABLE"]
BB_UNIMPORTANT_FEATURES = ["Block ID", "Block Name"]
BB_CPP_MEMORY_FEATURES = ["MemOps"]
BB_EXPLICIT_EXCLUDE_FEATURES = ["CondBranches", "InDirectCalls", "UnCondBranches", "MemOps"]
